* Support customization of grml2hd through /etc/grml2hd/customization.

diff --git a/grml2hd b/grml2hd
--- a/grml2hd
+++ b/grml2hd
@@ -4,11 +4,18 @@
 # Authors:       grml-team (grml.org), (c) Andreas Gredler <jimmy@grml.org>, Michael Prokop <mika@grml.org>
 # Bug-Reports:   see http://grml.org/bugs/
 # License:       This file is licensed under the GPL v2.
-# Latest change: Mon Okt 09 11:42:13 CEST 2006 [mika]
+# Latest change: Fre Okt 20 00:28:42 CEST 2006 [mika]
 ################################################################################
 
 LANG='C'
 LC_ALL='C'
+
+if [ -r /etc/grml2hd/customization ] ; then
+   . /etc/grml2hd/customization
+else
+   echo "Error: /etc/grml2hd/customization not found, exiting." >&2
+   exit 1
+fi
 
 function is_grml_small(){
   grep -q small /etc/grml_version && return 0 || return 1
@@ -19,10 +26,18 @@ function is_grml_usb(){
 }
 
 function is_grml2hd_noninteractive(){
-  if ! [ -z "$GRML2HD_NONINTERACTIVE" ] ; then
-     return 0 # we running automatic installation
+  if [ -n "$GRML2HD_NONINTERACTIVE" ] ; then
+     return 0 # we are running automatic installation
   else
      return 1 # we are running interactive installatio
+  fi
+}
+
+function checkvalue(){
+  if [ "$1" = "yes" ] ; then
+    return 0
+  else
+    return 1
   fi
 }
 
@@ -33,7 +48,7 @@ image=/boot/memtest86+.bin
 "
 
 # variables
-VERSION='0.8.11'
+VERSION='0.8.12'
 PN=$(basename "$0")
 PID="$(echo $$)"
 UNAME=$(uname -r)
@@ -60,7 +75,7 @@ function bailout(){
 
 trap bailout 1 2 3 15
 
-if ! [ -z "$NOSWREMOVAL" ] ; then
+if [ -n "$NOSWREMOVAL" ] ; then
   echo "NOSWREMOVAL=$NOSWREMOVAL" >> $CONFIGTMP
 fi
 
@@ -661,7 +676,7 @@ function finalize()
 }
 
 # if config file is present and we are running the non-interactive installation then source it:
-if ! [ -z "$GRML2HD_NONINTERACTIVE" ] ; then
+if [ -n "$GRML2HD_NONINTERACTIVE" ] ; then
    [ -r /etc/grml2hd/config ] && . /etc/grml2hd/config
 fi
 
@@ -770,28 +785,31 @@ fi
 }
 
 # now run the functions:
-is_grml2hd_noninteractive && if checkforrun ; then
- echo "Exiting as requested"
- bailout 14
-fi
-check4root
-check4mem
-is_grml2hd_noninteractive && PREEXECUTE # execute defined function in /etc/grml2hd/config
-welcome_screen
-partition_select
-check4partition
-check4space
-check4mbr
-lilo_sw_raid
-getfs
-initialize || initialize_error
-copy_files
-is_grml_small && grmlsmall_fixes
-create_fstab
-create_inittab
-get_bootparams
-create_liloconfig
-call_chroot
+checkvalue $GRML2HD_NONINTERACTIVE && (
+ is_grml2hd_noninteractive && \
+ if checkforrun ; then
+   echo "Exiting as requested"
+   bailout 14
+ fi
+)
+checkvalue $GRML2HD_CHECK4ROOT && check4root
+checkvalue $GRML2HD_CHECK4MEM && check4mem
+checkvalue $GRML2HD_NONINTERACTIVE && ( is_grml2hd_noninteractive && PREEXECUTE ) # execute defined function in /etc/grml2hd/config
+checkvalue $GRML2HD_WELCOME_SCREEN && welcome_screen
+checkvalue $GRML2HD_PARTITION_SELECT && partition_select
+checkvalue $GRML2HD_CHECK4PARTITION && check4partition
+checkvalue $GRML2HD_CHECK4SPACE && check4space
+checkvalue $GRML2HD_CHECK4MBR && check4mbr
+checkvalue $GRML2HD_LILO_SW_RAID && lilo_sw_raid
+checkvalue $GRML2HD_GETFS && getfs
+checkvalue $GRML2HD_INITIALIZE && ( initialize || initialize_error )
+checkvalue $GRML2HD_COPY_FILES && copy_files
+checkvalue $GRML2HD_IS_GRML_SMALL && ( is_grml_small && grmlsmall_fixes )
+checkvalue $GRML2HD_CREATE_FSTAB && create_fstab
+checkvalue $GRML2HD_CREATE_INITTAB && create_inittab
+checkvalue $GRML2HD_GET_BOOTPARAMS && get_bootparams
+checkvalue $GRML2HD_CREATE_LILOCONFIG && create_liloconfig
+checkvalue $GRML2HD_CALL_CHROOT && call_chroot
 
 # reiser4 :-(
  if [[ $FILESYSTEM == reiser4 ]] ; then
@@ -807,7 +825,7 @@ If this fails try it once more.
 Sorry for any inconvenience caused." 15 70
 fi
 
-finalize
+checkvalue $GRML2HD_FINALIZE && finalize
 
 rm -f $TMPFILE
 
