several updates in grub code

diff --git a/grml2hd-chrooted b/grml2hd-chrooted
--- a/grml2hd-chrooted
+++ b/grml2hd-chrooted
@@ -302,6 +302,68 @@ Error:
   fi
 }
 
+# get grub's syntax for /dev/ice
+# usage example: 'grubdevice /dev/hda2' returns '(hd0,1)'
+grubdevice() {
+  if [ -z "$1" ] ; then
+     echo "Usage: grubdevice <device>">&2
+     return 1
+  fi
+
+  device="$1"
+  device_map=/boot/grub/device.map
+
+  # create device.map
+  if ! [ -f "$device_map" ] ; then
+     grub --device-map="$device_map" | echo 'quit' 1>/dev/null
+  fi
+
+  # taken from d-i's trunk/packages/arch/i386/grub-installer/grub-installer:
+  tmp_disk=`echo "$device" | sed -e 's%\([sh]d[a-z]\)[0-9]*$%\1%' \
+                    -e 's%\(fd[0-9]*\)$%\1%' \
+                    -e 's%/part[0-9]*$%/disc%' \
+                    -e 's%\(c[0-7]d[0-9]*\).*$%\1%'`
+  tmp_part=`echo "$device" | sed -e 's%.*/[sh]d[a-z]\([0-9]*\)$%\1%' \
+                    -e 's%.*/fd[0-9]*$%%' \
+                    -e 's%.*/floppy/[0-9]*$%%' \
+                    -e 's%.*/\(disc\|part\([0-9]*\)\)$%\2%' \
+                    -e 's%.*c[0-7]d[0-9]*p*%%'`
+  tmp_drive=$(grep -v '^#' $device_map | grep "$tmp_disk *$" | sed 's%.*\(([hf]d[0-9][a-g0-9,]*)\).*%\1%')
+  GRUBSETUPDEVICE="$(echo "$tmp_drive")"
+  case $1 in
+     /dev/[sh]d[a-z]) # we expect something like '(hd0)'
+        GRUBDEVICE="$(echo "$tmp_drive")"
+        ;;
+      *) # we expect something like '(hd0,0)'
+        GRUBDEVICE="$(echo "$tmp_drive" | sed "s%)$%,`expr $tmp_part - 1`)%")"
+        # make sure we don't install into MBR if $USE_MBR is not set
+        [ -z "$USE_MBR" ] && GRUBSETUPDEVICE="$(echo "$tmp_drive" | sed "s%)$%,`expr $tmp_part - 1`)%")"
+        ;;
+  esac
+}
+
+grub_install() {
+  if ! [ -r /boot/grub/grml-template_menu.lst ] ; then
+     echo "Error: could not find /boot/grub/grml-template_menu.lst">&2
+     return 1
+  else
+     if [ -n "$GRUBDEVICE" ] ; then
+        cp /boot/grub/grml-template_menu.lst /boot/grub/menu.lst
+        sed -i "s/^# kopt=root=.*/# kopt=root=${ROOTPARTITION} ro/" /boot/grub/menu.lst
+        sed -i "s/^# groot=.*/# groot=${GRUBDEVICE}/"         /boot/grub/menu.lst
+
+        grubdevice "$BOOT_PARTITION"
+        update-grub -y
+        
+        echo -en "root ${GRUBDEVICE}\nsetup ${GRUBSETUPDEVICE}\n" | grub install
+
+     else
+        echo "Error: could not find a grub device">&2
+        return 1
+     fi
+  fi
+}
+
 fix_sysvinit() {
   dpkg --purge grml-sysvinit 1>/dev/null 2>&1
   cp /sbin/init /etc 1>/dev/null 2>&1
@@ -412,7 +474,8 @@ if checkvalue $CHROOT_INSTALL_LILO ; then
     echo "XXX";
     echo "Running lilo..."
     echo "XXX";
-    install_lilo
+    # install_lilo
+    grub_install
     echo "100") | \
   dialog --title "${PN}" --gauge "Running lilo..." 9 50 0
 fi
